import { Epic, Organization, Slice, Ticket } from "./types"

export const mockOrganizations: Organization[] = [
  {
    id: "telemetryops",
    name: "telemetryops",
    displayName: "TelemetryOps",
  },
  {
    id: "ballotradar",
    name: "ballotradar",
    displayName: "BallotRadar",
  },
]

export const mockEpics: Epic[] = [
  // TelemetryOps Epics
  {
    id: "epic-1",
    title: "Bootstrap Multi-Account Infrastructure",
    description: "Set up OIDC authentication and Terraform state management across dev, shared, and prod accounts",
    status: "COMPLETED",
    organization: "telemetryops",
    createdAt: "2024-12-01T10:00:00Z",
    updatedAt: "2024-12-15T14:30:00Z",
  },
  {
    id: "epic-2",
    title: "Implement Billing Alarms",
    description: "Create CloudWatch alarms and SNS notifications for cost monitoring across all AWS accounts",
    status: "IN_PROGRESS",
    organization: "telemetryops",
    createdAt: "2024-12-10T09:00:00Z",
    updatedAt: "2025-01-02T11:15:00Z",
  },
  {
    id: "epic-3",
    title: "DNS Infrastructure Setup",
    description: "Configure Route53 hosted zones and cross-account delegation for telemetryops.com",
    status: "PENDING",
    organization: "telemetryops",
    createdAt: "2024-12-20T08:00:00Z",
    updatedAt: "2024-12-20T08:00:00Z",
  },
  {
    id: "epic-4",
    title: "NixOS Builder Automation",
    description: "Build automated SD card image generator for Mac Mini deployment infrastructure",
    status: "PENDING",
    organization: "telemetryops",
    createdAt: "2025-01-03T10:00:00Z",
    updatedAt: "2025-01-03T10:00:00Z",
  },

  // BallotRadar Epics
  {
    id: "epic-5",
    title: "WebAuthn Authentication System",
    description: "Implement passwordless authentication using WebAuthn passkeys with API Gateway and Lambda",
    status: "IN_PROGRESS",
    organization: "ballotradar",
    createdAt: "2024-11-15T10:00:00Z",
    updatedAt: "2025-01-01T16:45:00Z",
  },
  {
    id: "epic-6",
    title: "Voter Database Schema Design",
    description: "Design and implement PostgreSQL RDS schema for voters, election history, and elections tables",
    status: "COMPLETED",
    organization: "ballotradar",
    createdAt: "2024-11-01T09:00:00Z",
    updatedAt: "2024-11-28T15:20:00Z",
  },
  {
    id: "epic-7",
    title: "Frontend Amplify Deployment",
    description: "Set up Next.js 15.5.3 frontend with Amplify hosting for dev and production environments",
    status: "IN_PROGRESS",
    organization: "ballotradar",
    createdAt: "2024-12-05T11:00:00Z",
    updatedAt: "2025-01-04T09:30:00Z",
  },
  {
    id: "epic-8",
    title: "Organization Management API",
    description: "Build RESTful API for managing organizations and organization admin permissions",
    status: "PENDING",
    organization: "ballotradar",
    createdAt: "2024-12-15T10:00:00Z",
    updatedAt: "2024-12-15T10:00:00Z",
  },
  {
    id: "epic-9",
    title: "Multi-Account DNS Architecture",
    description: "Implement cross-account Route53 delegation for ballotradar.com with dev and prod subdomains",
    status: "BLOCKED",
    organization: "ballotradar",
    createdAt: "2024-12-01T08:00:00Z",
    updatedAt: "2024-12-22T13:10:00Z",
  },
]

export const mockSlices: Slice[] = [
  // Epic 1: Bootstrap Multi-Account Infrastructure
  {
    id: "slice-1-1",
    epicId: "epic-1",
    title: "Set up GitHub OIDC provider",
    description: "Configure OIDC identity provider in AWS IAM for GitHub Actions authentication",
    status: "COMPLETED",
    createdAt: "2024-12-01T10:00:00Z",
    updatedAt: "2024-12-05T14:00:00Z",
  },
  {
    id: "slice-1-2",
    epicId: "epic-1",
    title: "Create Terraform state S3 buckets",
    description: "Deploy S3 buckets and DynamoDB tables for Terraform remote state management",
    status: "COMPLETED",
    createdAt: "2024-12-05T10:00:00Z",
    updatedAt: "2024-12-10T16:00:00Z",
  },
  {
    id: "slice-1-3",
    epicId: "epic-1",
    title: "Configure cross-account IAM roles",
    description: "Set up IAM roles for cross-account access between dev, shared, and prod",
    status: "COMPLETED",
    createdAt: "2024-12-10T10:00:00Z",
    updatedAt: "2024-12-15T14:30:00Z",
  },

  // Epic 2: Implement Billing Alarms
  {
    id: "slice-2-1",
    epicId: "epic-2",
    title: "Create CloudWatch billing alarms",
    description: "Set up CloudWatch alarms for AWS billing thresholds across all accounts",
    status: "COMPLETED",
    createdAt: "2024-12-10T09:00:00Z",
    updatedAt: "2024-12-28T15:00:00Z",
  },
  {
    id: "slice-2-2",
    epicId: "epic-2",
    title: "Configure SNS notification topics",
    description: "Create SNS topics and subscriptions for alarm notifications",
    status: "IN_PROGRESS",
    createdAt: "2024-12-20T10:00:00Z",
    updatedAt: "2025-01-02T11:15:00Z",
  },
  {
    id: "slice-2-3",
    epicId: "epic-2",
    title: "Set up email alerting",
    description: "Configure email endpoints and test alarm notification delivery",
    status: "PENDING",
    createdAt: "2024-12-28T10:00:00Z",
    updatedAt: "2024-12-28T10:00:00Z",
  },

  // Epic 3: DNS Infrastructure Setup
  {
    id: "slice-3-1",
    epicId: "epic-3",
    title: "Create Route53 hosted zones",
    description: "Set up hosted zones in dev, shared, and prod accounts",
    status: "PENDING",
    createdAt: "2024-12-20T08:00:00Z",
    updatedAt: "2024-12-20T08:00:00Z",
  },
  {
    id: "slice-3-2",
    epicId: "epic-3",
    title: "Configure NS record delegation",
    description: "Set up cross-account DNS delegation with NS records",
    status: "PENDING",
    createdAt: "2024-12-20T08:00:00Z",
    updatedAt: "2024-12-20T08:00:00Z",
  },
  {
    id: "slice-3-3",
    epicId: "epic-3",
    title: "Test DNS resolution",
    description: "Verify DNS propagation and resolution across all environments",
    status: "PENDING",
    createdAt: "2024-12-20T08:00:00Z",
    updatedAt: "2024-12-20T08:00:00Z",
  },

  // Epic 4: NixOS Builder Automation
  {
    id: "slice-4-1",
    epicId: "epic-4",
    title: "Create NixOS configuration",
    description: "Design NixOS system configuration for Mac Mini deployment",
    status: "PENDING",
    createdAt: "2025-01-03T10:00:00Z",
    updatedAt: "2025-01-03T10:00:00Z",
  },
  {
    id: "slice-4-2",
    epicId: "epic-4",
    title: "Build SD card image generator",
    description: "Implement automated script to generate bootable SD card images",
    status: "PENDING",
    createdAt: "2025-01-03T10:00:00Z",
    updatedAt: "2025-01-03T10:00:00Z",
  },
  {
    id: "slice-4-3",
    epicId: "epic-4",
    title: "Add CI/CD pipeline",
    description: "Set up GitHub Actions workflow for automated image builds",
    status: "PENDING",
    createdAt: "2025-01-03T10:00:00Z",
    updatedAt: "2025-01-03T10:00:00Z",
  },

  // Epic 5: WebAuthn Authentication System
  {
    id: "slice-5-1",
    epicId: "epic-5",
    title: "Implement WebAuthn registration",
    description: "Build Lambda function for passkey registration flow",
    status: "COMPLETED",
    createdAt: "2024-11-15T10:00:00Z",
    updatedAt: "2024-12-01T14:00:00Z",
  },
  {
    id: "slice-5-2",
    epicId: "epic-5",
    title: "Implement WebAuthn authentication",
    description: "Build Lambda function for passkey authentication flow",
    status: "IN_PROGRESS",
    createdAt: "2024-12-01T10:00:00Z",
    updatedAt: "2025-01-01T16:45:00Z",
  },
  {
    id: "slice-5-3",
    epicId: "epic-5",
    title: "Configure API Gateway endpoints",
    description: "Set up API Gateway routes for auth endpoints",
    status: "COMPLETED",
    createdAt: "2024-11-20T10:00:00Z",
    updatedAt: "2024-12-05T15:00:00Z",
  },
  {
    id: "slice-5-4",
    epicId: "epic-5",
    title: "Create DynamoDB tables",
    description: "Design and deploy DynamoDB tables for credential storage",
    status: "COMPLETED",
    createdAt: "2024-11-18T10:00:00Z",
    updatedAt: "2024-11-25T16:00:00Z",
  },

  // Epic 6: Voter Database Schema Design
  {
    id: "slice-6-1",
    epicId: "epic-6",
    title: "Design voters table schema",
    description: "Create schema for voter information and registration data",
    status: "COMPLETED",
    createdAt: "2024-11-01T09:00:00Z",
    updatedAt: "2024-11-10T14:00:00Z",
  },
  {
    id: "slice-6-2",
    epicId: "epic-6",
    title: "Design elections table schema",
    description: "Create schema for election definitions and metadata",
    status: "COMPLETED",
    createdAt: "2024-11-10T09:00:00Z",
    updatedAt: "2024-11-18T15:00:00Z",
  },
  {
    id: "slice-6-3",
    epicId: "epic-6",
    title: "Design election_history table schema",
    description: "Create schema for tracking voter participation history",
    status: "COMPLETED",
    createdAt: "2024-11-18T09:00:00Z",
    updatedAt: "2024-11-28T15:20:00Z",
  },

  // Epic 7: Frontend Amplify Deployment
  {
    id: "slice-7-1",
    epicId: "epic-7",
    title: "Set up Next.js 15.5.3 project",
    description: "Initialize Next.js project with TypeScript and required dependencies",
    status: "COMPLETED",
    createdAt: "2024-12-05T11:00:00Z",
    updatedAt: "2024-12-12T16:00:00Z",
  },
  {
    id: "slice-7-2",
    epicId: "epic-7",
    title: "Configure Amplify hosting",
    description: "Set up Amplify apps for dev.ballotradar.com and www.ballotradar.com",
    status: "IN_PROGRESS",
    createdAt: "2024-12-12T11:00:00Z",
    updatedAt: "2025-01-04T09:30:00Z",
  },
  {
    id: "slice-7-3",
    epicId: "epic-7",
    title: "Implement shadcn/ui components",
    description: "Add and configure shadcn/ui component library",
    status: "COMPLETED",
    createdAt: "2024-12-15T10:00:00Z",
    updatedAt: "2024-12-20T14:00:00Z",
  },
  {
    id: "slice-7-4",
    epicId: "epic-7",
    title: "Set up CI/CD pipeline",
    description: "Configure GitHub Actions for automated deployments",
    status: "PENDING",
    createdAt: "2024-12-20T10:00:00Z",
    updatedAt: "2024-12-20T10:00:00Z",
  },

  // Epic 8: Organization Management API
  {
    id: "slice-8-1",
    epicId: "epic-8",
    title: "Design API schema",
    description: "Define RESTful API endpoints and request/response schemas",
    status: "PENDING",
    createdAt: "2024-12-15T10:00:00Z",
    updatedAt: "2024-12-15T10:00:00Z",
  },
  {
    id: "slice-8-2",
    epicId: "epic-8",
    title: "Implement Lambda functions",
    description: "Build Lambda functions for CRUD operations on organizations",
    status: "PENDING",
    createdAt: "2024-12-15T10:00:00Z",
    updatedAt: "2024-12-15T10:00:00Z",
  },
  {
    id: "slice-8-3",
    epicId: "epic-8",
    title: "Add authorization layer",
    description: "Implement permission checks for organization admin access",
    status: "PENDING",
    createdAt: "2024-12-15T10:00:00Z",
    updatedAt: "2024-12-15T10:00:00Z",
  },

  // Epic 9: Multi-Account DNS Architecture
  {
    id: "slice-9-1",
    epicId: "epic-9",
    title: "Create shared account hosted zone",
    description: "Set up root ballotradar.com hosted zone in shared account",
    status: "COMPLETED",
    createdAt: "2024-12-01T08:00:00Z",
    updatedAt: "2024-12-08T15:00:00Z",
  },
  {
    id: "slice-9-2",
    epicId: "epic-9",
    title: "Create dev/prod hosted zones",
    description: "Set up subdomain hosted zones in dev and prod accounts",
    status: "COMPLETED",
    createdAt: "2024-12-08T10:00:00Z",
    updatedAt: "2024-12-15T14:00:00Z",
  },
  {
    id: "slice-9-3",
    epicId: "epic-9",
    title: "Configure NS delegation",
    description: "Set up NS record delegation from shared to dev/prod",
    status: "BLOCKED",
    createdAt: "2024-12-15T10:00:00Z",
    updatedAt: "2024-12-22T13:10:00Z",
  },
]

export const mockTickets: Ticket[] = [
  // Tickets for slice-1-1 (Set up GitHub OIDC provider)
  {
    id: "ticket-1-1-1",
    sliceId: "slice-1-1",
    title: "Research AWS OIDC provider setup requirements",
    type: "task",
    status: "COMPLETED",
    intent: "Understand AWS OIDC provider requirements and GitHub Actions integration patterns to ensure secure authentication setup",
    notes: "Reviewed AWS documentation on OIDC identity providers. Key findings: need to configure thumbprint, audience claim, and trust policy. GitHub provides token.actions.githubusercontent.com as the provider URL.",
    blocks: ["ticket-1-1-2"],
    blockedBy: [],
    causedBy: null,
    createdAt: "2024-12-01T10:00:00Z",
    updatedAt: "2024-12-02T14:00:00Z",
  },
  {
    id: "ticket-1-1-2",
    sliceId: "slice-1-1",
    title: "Create IAM OIDC identity provider in AWS console",
    type: "task",
    status: "COMPLETED",
    intent: "Create the OIDC identity provider resource in AWS IAM to enable GitHub Actions authentication",
    notes: "Created OIDC provider with URL: token.actions.githubusercontent.com. Added audience: sts.amazonaws.com. Thumbprint configured automatically by AWS.",
    blocks: ["ticket-1-1-3"],
    blockedBy: ["ticket-1-1-1"],
    causedBy: null,
    createdAt: "2024-12-02T10:00:00Z",
    updatedAt: "2024-12-03T15:00:00Z",
  },
  {
    id: "ticket-1-1-3",
    sliceId: "slice-1-1",
    title: "Configure GitHub Actions trust relationship",
    type: "task",
    status: "COMPLETED",
    intent: "Set up IAM role with trust policy allowing GitHub Actions to assume the role via OIDC",
    notes: "Created IAM role with trust policy allowing token.actions.githubusercontent.com. Added condition to restrict to specific repository. Attached deployment permissions policy.",
    blocks: ["ticket-1-1-4"],
    blockedBy: ["ticket-1-1-2"],
    causedBy: null,
    createdAt: "2024-12-03T10:00:00Z",
    updatedAt: "2024-12-04T16:00:00Z",
  },
  {
    id: "ticket-1-1-4",
    sliceId: "slice-1-1",
    title: "Test OIDC authentication from GitHub Actions",
    type: "task",
    status: "COMPLETED",
    intent: "Verify that GitHub Actions can successfully authenticate to AWS using OIDC and assume the configured role",
    notes: "Created test workflow that uses aws-actions/configure-aws-credentials. Successfully assumed role and ran aws sts get-caller-identity. Authentication working as expected.",
    blocks: ["ticket-1-1-5"],
    blockedBy: ["ticket-1-1-3"],
    causedBy: null,
    createdAt: "2024-12-04T10:00:00Z",
    updatedAt: "2024-12-05T14:00:00Z",
  },
  {
    id: "ticket-1-1-5",
    sliceId: "slice-1-1",
    title: "Document OIDC setup process",
    type: "chore",
    status: "COMPLETED",
    intent: "Create comprehensive documentation for future reference and team onboarding on OIDC setup",
    notes: "Added documentation to repository wiki covering: provider setup, role configuration, trust policy details, and example GitHub Actions workflow. Included troubleshooting section.",
    blocks: [],
    blockedBy: ["ticket-1-1-4"],
    causedBy: null,
    createdAt: "2024-12-05T10:00:00Z",
    updatedAt: "2024-12-05T14:00:00Z",
  },

  // Tickets for slice-1-2 (Create Terraform state S3 buckets)
  {
    id: "ticket-1-2-1",
    sliceId: "slice-1-2",
    title: "Design S3 bucket naming convention",
    type: "task",
    status: "COMPLETED",
    intent: "Establish consistent naming convention for Terraform state buckets across all AWS accounts",
    notes: "Decided on pattern: telemetryops-terraform-state-{account}. Ensures uniqueness and clear identification of purpose and environment.",
    blocks: ["ticket-1-2-2"],
    blockedBy: [],
    causedBy: null,
    createdAt: "2024-12-05T10:00:00Z",
    updatedAt: "2024-12-06T14:00:00Z",
  },
  {
    id: "ticket-1-2-2",
    sliceId: "slice-1-2",
    title: "Create S3 buckets for dev, shared, prod",
    type: "task",
    status: "COMPLETED",
    intent: "Deploy S3 buckets in each account to store Terraform state files with proper isolation",
    notes: "Created buckets: telemetryops-terraform-state-dev, telemetryops-terraform-state-shared, telemetryops-terraform-state-prod. All buckets created in us-east-1.",
    blocks: ["ticket-1-2-3"],
    blockedBy: ["ticket-1-2-1"],
    causedBy: null,
    createdAt: "2024-12-06T10:00:00Z",
    updatedAt: "2024-12-07T15:00:00Z",
  },
  {
    id: "ticket-1-2-3",
    sliceId: "slice-1-2",
    title: "Enable S3 bucket versioning and encryption",
    type: "task",
    status: "COMPLETED",
    intent: "Enable versioning for state file recovery and encryption for security compliance",
    notes: "Enabled versioning on all buckets. Configured AES-256 server-side encryption. Set lifecycle policy to transition old versions to Glacier after 90 days.",
    blocks: ["ticket-1-2-4"],
    blockedBy: ["ticket-1-2-2"],
    causedBy: null,
    createdAt: "2024-12-07T10:00:00Z",
    updatedAt: "2024-12-08T16:00:00Z",
  },
  {
    id: "ticket-1-2-4",
    sliceId: "slice-1-2",
    title: "Create DynamoDB table for state locking",
    type: "task",
    status: "COMPLETED",
    intent: "Create DynamoDB table to prevent concurrent Terraform operations and state corruption",
    notes: "Created table: terraform-state-lock with LockID as partition key. Configured on-demand billing. Table supports Terraform state locking mechanism.",
    blocks: ["ticket-1-2-5"],
    blockedBy: ["ticket-1-2-3"],
    causedBy: null,
    createdAt: "2024-12-08T10:00:00Z",
    updatedAt: "2024-12-09T14:00:00Z",
  },
  {
    id: "ticket-1-2-5",
    sliceId: "slice-1-2",
    title: "Configure bucket policies for least privilege access",
    type: "task",
    status: "COMPLETED",
    intent: "Implement least privilege bucket policies to restrict access to authorized roles only",
    notes: "Applied bucket policies allowing access only from GitHub Actions OIDC role and admin role. Denied unencrypted uploads. Tested with deployment pipeline.",
    blocks: [],
    blockedBy: ["ticket-1-2-4"],
    causedBy: null,
    createdAt: "2024-12-09T10:00:00Z",
    updatedAt: "2024-12-10T16:00:00Z",
  },

  // Tickets for slice-2-1 (Create CloudWatch billing alarms)
  {
    id: "ticket-2-1-1",
    sliceId: "slice-2-1",
    title: "Define billing thresholds for each account",
    type: "task",
    status: "COMPLETED",
    intent: "Establish appropriate billing thresholds for monitoring AWS costs across different account types",
    notes: "Set thresholds: dev $50/month, shared $100/month, prod $200/month. Based on projected usage and early warning needs.",
    blocks: ["ticket-2-1-2", "ticket-2-1-3", "ticket-2-1-4"],
    blockedBy: [],
    causedBy: null,
    createdAt: "2024-12-10T09:00:00Z",
    updatedAt: "2024-12-12T14:00:00Z",
  },
  {
    id: "ticket-2-1-2",
    sliceId: "slice-2-1",
    title: "Create CloudWatch alarm for dev account",
    type: "task",
    status: "COMPLETED",
    intent: "Set up billing alarm in dev account to monitor and alert on unexpected cost increases",
    notes: "Created alarm with $50 threshold. Configured to trigger when EstimatedCharges exceeds threshold for 6 hours. Linked to SNS topic billing-alerts-dev.",
    blocks: [],
    blockedBy: ["ticket-2-1-1"],
    causedBy: null,
    createdAt: "2024-12-12T10:00:00Z",
    updatedAt: "2024-12-15T15:00:00Z",
  },
  {
    id: "ticket-2-1-3",
    sliceId: "slice-2-1",
    title: "Create CloudWatch alarm for shared account",
    type: "task",
    status: "COMPLETED",
    intent: "Set up billing alarm in shared account to monitor infrastructure costs",
    notes: "Created alarm with $100 threshold. Same configuration as dev account. Linked to SNS topic billing-alerts-shared.",
    blocks: [],
    blockedBy: ["ticket-2-1-1"],
    causedBy: null,
    createdAt: "2024-12-15T10:00:00Z",
    updatedAt: "2024-12-18T16:00:00Z",
  },
  {
    id: "ticket-2-1-4",
    sliceId: "slice-2-1",
    title: "Create CloudWatch alarm for prod account",
    type: "task",
    status: "COMPLETED",
    intent: "Set up billing alarm in prod account with higher threshold for production workloads",
    notes: "Created alarm with $200 threshold. Configured same monitoring period. Linked to SNS topic billing-alerts-prod.",
    blocks: ["ticket-2-1-5"],
    blockedBy: ["ticket-2-1-1"],
    causedBy: null,
    createdAt: "2024-12-18T10:00:00Z",
    updatedAt: "2024-12-22T14:00:00Z",
  },
  {
    id: "ticket-2-1-5",
    sliceId: "slice-2-1",
    title: "Test alarm triggering with simulated costs",
    type: "task",
    status: "COMPLETED",
    intent: "Verify that alarms trigger correctly and notifications are sent when thresholds are exceeded",
    notes: "Used CloudWatch metric publishing to simulate threshold breach. Confirmed all three alarms triggered correctly and sent notifications to SNS topics.",
    blocks: [],
    blockedBy: ["ticket-2-1-4"],
    causedBy: null,
    createdAt: "2024-12-22T10:00:00Z",
    updatedAt: "2024-12-28T15:00:00Z",
  },

  // Tickets for slice-2-2 (Configure SNS notification topics)
  {
    id: "ticket-2-2-1",
    sliceId: "slice-2-2",
    title: "Create SNS topics for each account",
    type: "task",
    status: "COMPLETED",
    intent: "Create SNS topics to receive and distribute billing alarm notifications",
    notes: "Created topics: billing-alerts-dev, billing-alerts-shared, billing-alerts-prod. All configured with display names for easy identification in emails.",
    blocks: ["ticket-2-2-2"],
    blockedBy: [],
    causedBy: null,
    createdAt: "2024-12-20T10:00:00Z",
    updatedAt: "2024-12-23T14:00:00Z",
  },
  {
    id: "ticket-2-2-2",
    sliceId: "slice-2-2",
    title: "Configure topic access policies",
    type: "task",
    status: "IN_PROGRESS",
    intent: "Set up access policies allowing CloudWatch to publish to SNS topics while restricting unauthorized access",
    notes: "Working on policies for each topic. Allowing CloudWatch service to publish messages. Need to add conditions for principal verification.",
    blocks: ["ticket-2-2-3"],
    blockedBy: ["ticket-2-2-1"],
    causedBy: null,
    createdAt: "2024-12-23T10:00:00Z",
    updatedAt: "2025-01-02T11:15:00Z",
  },
  {
    id: "ticket-2-2-3",
    sliceId: "slice-2-2",
    title: "Link SNS topics to CloudWatch alarms",
    type: "task",
    status: "PENDING",
    intent: "Connect CloudWatch billing alarms to SNS topics to enable notification delivery",
    notes: "Waiting for topic access policies to be finalized before linking alarms.",
    blocks: ["ticket-2-2-4"],
    blockedBy: ["ticket-2-2-2"],
    causedBy: null,
    createdAt: "2024-12-26T10:00:00Z",
    updatedAt: "2024-12-26T10:00:00Z",
  },
  {
    id: "ticket-2-2-4",
    sliceId: "slice-2-2",
    title: "Test SNS message delivery",
    type: "task",
    status: "PENDING",
    intent: "Verify end-to-end notification flow from CloudWatch alarms through SNS to email subscribers",
    notes: "Will test by manually publishing test messages to each SNS topic.",
    blocks: [],
    blockedBy: ["ticket-2-2-3"],
    causedBy: null,
    createdAt: "2024-12-28T10:00:00Z",
    updatedAt: "2024-12-28T10:00:00Z",
  },

  // Tickets for slice-5-2 (Implement WebAuthn authentication)
  {
    id: "ticket-5-2-1",
    sliceId: "slice-5-2",
    title: "Implement credential verification logic",
    type: "feature",
    status: "COMPLETED",
    intent: "Build the core logic to verify WebAuthn credentials against stored public keys",
    notes: "Implemented verification using @simplewebauthn/server library. Validates authenticator data, client data, and signature. Retrieves stored credentials from DynamoDB for comparison.",
    blocks: ["ticket-5-2-2"],
    blockedBy: [],
    causedBy: null,
    createdAt: "2024-12-01T10:00:00Z",
    updatedAt: "2024-12-10T14:00:00Z",
  },
  {
    id: "ticket-5-2-2",
    sliceId: "slice-5-2",
    title: "Add session token generation",
    type: "feature",
    status: "COMPLETED",
    intent: "Generate secure JWT session tokens after successful authentication",
    notes: "Using jose library to generate JWTs with 1-hour expiration. Tokens include user ID, credential ID, and authentication timestamp. Signed with RS256.",
    blocks: ["ticket-5-2-3"],
    blockedBy: ["ticket-5-2-1"],
    causedBy: null,
    createdAt: "2024-12-10T10:00:00Z",
    updatedAt: "2024-12-15T15:00:00Z",
  },
  {
    id: "ticket-5-2-3",
    sliceId: "slice-5-2",
    title: "Implement challenge-response flow",
    type: "feature",
    status: "IN_PROGRESS",
    intent: "Build the complete authentication challenge generation and response verification flow",
    notes: "Challenge generation complete. Working on response verification integration with credential verification logic. Need to handle edge cases for expired challenges.",
    blocks: ["ticket-5-2-4", "ticket-5-2-5"],
    blockedBy: ["ticket-5-2-2"],
    causedBy: null,
    createdAt: "2024-12-15T10:00:00Z",
    updatedAt: "2025-01-01T16:45:00Z",
  },
  {
    id: "ticket-5-2-4",
    sliceId: "slice-5-2",
    title: "Add error handling for invalid credentials",
    type: "bug",
    status: "PENDING",
    intent: "Implement proper error responses and logging for authentication failures",
    notes: "Need to add error codes for: credential not found, signature mismatch, challenge expired, invalid authenticator data.",
    blocks: [],
    blockedBy: ["ticket-5-2-3"],
    causedBy: "ticket-5-2-3",
    createdAt: "2024-12-20T10:00:00Z",
    updatedAt: "2024-12-20T10:00:00Z",
  },
  {
    id: "ticket-5-2-5",
    sliceId: "slice-5-2",
    title: "Write unit tests for authentication flow",
    type: "task",
    status: "PENDING",
    intent: "Create comprehensive unit tests covering all authentication scenarios including failures",
    notes: "Test cases needed for: successful auth, invalid signature, expired challenge, missing credential, malformed request.",
    blocks: [],
    blockedBy: ["ticket-5-2-3"],
    causedBy: null,
    createdAt: "2024-12-22T10:00:00Z",
    updatedAt: "2024-12-22T10:00:00Z",
  },

  // Tickets for slice-7-2 (Configure Amplify hosting)
  {
    id: "ticket-7-2-1",
    sliceId: "slice-7-2",
    title: "Create Amplify app for dev environment",
    type: "task",
    status: "COMPLETED",
    intent: "Set up Amplify app instance in dev account for hosting the development frontend",
    notes: "Created Amplify app named 'ballotradar-dev'. Connected to GitHub repository. Configured build settings for Next.js 15.5.3.",
    blocks: ["ticket-7-2-3"],
    blockedBy: [],
    causedBy: null,
    createdAt: "2024-12-12T11:00:00Z",
    updatedAt: "2024-12-15T14:00:00Z",
  },
  {
    id: "ticket-7-2-2",
    sliceId: "slice-7-2",
    title: "Create Amplify app for prod environment",
    type: "task",
    status: "COMPLETED",
    intent: "Set up Amplify app instance in prod account for hosting the production frontend",
    notes: "Created Amplify app named 'ballotradar-prod'. Connected to main branch. Same build configuration as dev.",
    blocks: ["ticket-7-2-4"],
    blockedBy: [],
    causedBy: null,
    createdAt: "2024-12-15T11:00:00Z",
    updatedAt: "2024-12-18T15:00:00Z",
  },
  {
    id: "ticket-7-2-3",
    sliceId: "slice-7-2",
    title: "Configure custom domain dev.ballotradar.com",
    type: "task",
    status: "IN_PROGRESS",
    intent: "Attach custom domain dev.ballotradar.com to the dev Amplify app",
    notes: "Added domain to Amplify. Waiting for DNS validation to complete. ACM certificate requested and pending validation.",
    blocks: ["ticket-7-2-5"],
    blockedBy: ["ticket-7-2-1"],
    causedBy: null,
    createdAt: "2024-12-18T11:00:00Z",
    updatedAt: "2025-01-04T09:30:00Z",
  },
  {
    id: "ticket-7-2-4",
    sliceId: "slice-7-2",
    title: "Configure custom domain www.ballotradar.com",
    type: "task",
    status: "PENDING",
    intent: "Attach custom domain www.ballotradar.com to the prod Amplify app",
    notes: "Waiting for dev domain configuration to complete successfully before configuring prod.",
    blocks: ["ticket-7-2-5"],
    blockedBy: ["ticket-7-2-2"],
    causedBy: null,
    createdAt: "2024-12-20T11:00:00Z",
    updatedAt: "2024-12-20T11:00:00Z",
  },
  {
    id: "ticket-7-2-5",
    sliceId: "slice-7-2",
    title: "Set up SSL certificates",
    type: "task",
    status: "PENDING",
    intent: "Verify SSL certificates are properly configured and domains are using HTTPS",
    notes: "ACM certificates should be auto-provisioned by Amplify. Need to verify after domain configurations complete.",
    blocks: ["ticket-7-2-6"],
    blockedBy: ["ticket-7-2-3", "ticket-7-2-4"],
    causedBy: null,
    createdAt: "2024-12-22T11:00:00Z",
    updatedAt: "2024-12-22T11:00:00Z",
  },
  {
    id: "ticket-7-2-6",
    sliceId: "slice-7-2",
    title: "Configure branch-based deployments",
    type: "feature",
    status: "PENDING",
    intent: "Enable automatic deployments for feature branches to preview environments",
    notes: "Set up pattern-based branch detection. Feature branches should deploy to temporary preview URLs.",
    blocks: [],
    blockedBy: ["ticket-7-2-5"],
    causedBy: null,
    createdAt: "2024-12-24T11:00:00Z",
    updatedAt: "2024-12-24T11:00:00Z",
  },

  // Tickets for slice-9-3 (Configure NS delegation) - BLOCKED
  {
    id: "ticket-9-3-1",
    sliceId: "slice-9-3",
    title: "Extract NS records from dev account",
    type: "task",
    status: "COMPLETED",
    intent: "Retrieve nameserver records from dev account hosted zone for delegation setup",
    notes: "Extracted NS records: ns-1234.awsdns-01.org, ns-5678.awsdns-02.com, ns-9012.awsdns-03.net, ns-3456.awsdns-04.co.uk",
    blocks: ["ticket-9-3-3"],
    blockedBy: [],
    causedBy: null,
    createdAt: "2024-12-15T10:00:00Z",
    updatedAt: "2024-12-16T14:00:00Z",
  },
  {
    id: "ticket-9-3-2",
    sliceId: "slice-9-3",
    title: "Extract NS records from prod account",
    type: "task",
    status: "COMPLETED",
    intent: "Retrieve nameserver records from prod account hosted zone for delegation setup",
    notes: "Extracted NS records: ns-7890.awsdns-05.org, ns-2345.awsdns-06.com, ns-6789.awsdns-07.net, ns-0123.awsdns-08.co.uk",
    blocks: ["ticket-9-3-3"],
    blockedBy: [],
    causedBy: null,
    createdAt: "2024-12-16T10:00:00Z",
    updatedAt: "2024-12-17T15:00:00Z",
  },
  {
    id: "ticket-9-3-3",
    sliceId: "slice-9-3",
    title: "Create NS records in shared account",
    type: "task",
    status: "BLOCKED",
    intent: "Add NS records in shared account to delegate subdomain resolution to dev and prod accounts",
    notes: "Attempted to create NS records but encountered IAM permissions error. Route53:ChangeResourceRecordSets permission denied.",
    blocks: ["ticket-9-3-5"],
    blockedBy: ["ticket-9-3-1", "ticket-9-3-2", "ticket-9-3-4"],
    causedBy: null,
    createdAt: "2024-12-17T10:00:00Z",
    updatedAt: "2024-12-22T13:10:00Z",
  },
  {
    id: "ticket-9-3-4",
    sliceId: "slice-9-3",
    title: "Fix IAM permissions issue blocking NS record creation",
    type: "bug",
    status: "BLOCKED",
    intent: "Resolve IAM permission error preventing NS record creation in shared account",
    notes: "GitHub Actions role lacks Route53:ChangeResourceRecordSets permission for shared account hosted zone. Need to update IAM policy. Waiting on account admin approval.",
    blocks: ["ticket-9-3-3"],
    blockedBy: [],
    causedBy: "ticket-9-3-3",
    createdAt: "2024-12-20T10:00:00Z",
    updatedAt: "2024-12-22T13:10:00Z",
  },
  {
    id: "ticket-9-3-5",
    sliceId: "slice-9-3",
    title: "Verify DNS delegation propagation",
    type: "task",
    status: "PENDING",
    intent: "Confirm DNS delegation is working correctly and subdomains resolve to correct accounts",
    notes: "Will test using dig commands to query dev.ballotradar.com and www.ballotradar.com nameservers.",
    blocks: [],
    blockedBy: ["ticket-9-3-3"],
    causedBy: null,
    createdAt: "2024-12-22T10:00:00Z",
    updatedAt: "2024-12-22T10:00:00Z",
  },
]

export function getOrganizations(): Organization[] {
  return mockOrganizations
}

export function getEpicsByOrganization(organizationId: string): Epic[] {
  return mockEpics.filter(epic => epic.organization === organizationId)
}

export function getEpicById(epicId: string): Epic | undefined {
  return mockEpics.find(epic => epic.id === epicId)
}

export function getSlicesByEpicId(epicId: string): Slice[] {
  return mockSlices.filter(slice => slice.epicId === epicId)
}

export function getSliceById(sliceId: string): Slice | undefined {
  return mockSlices.find(slice => slice.id === sliceId)
}

export function getTicketsBySliceId(sliceId: string): Ticket[] {
  return mockTickets.filter(ticket => ticket.sliceId === sliceId)
}

export function getTicketById(ticketId: string): Ticket | undefined {
  return mockTickets.find(ticket => ticket.id === ticketId)
}
